/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_benchmarkresult_free: (a: number, b: number) => void;
export const __wbg_get_benchmarkresult_avg: (a: number) => number;
export const __wbg_get_benchmarkresult_max: (a: number) => number;
export const __wbg_get_benchmarkresult_min: (a: number) => number;
export const __wbg_get_benchmarkresult_total: (a: number) => number;
export const __wbg_get_benchmarkresult_tps: (a: number) => number;
export const __wbg_set_benchmarkresult_avg: (a: number, b: number) => void;
export const __wbg_set_benchmarkresult_max: (a: number, b: number) => void;
export const __wbg_set_benchmarkresult_min: (a: number, b: number) => void;
export const __wbg_set_benchmarkresult_total: (a: number, b: number) => void;
export const __wbg_set_benchmarkresult_tps: (a: number, b: number) => void;
export const __wbg_universe_free: (a: number, b: number) => void;
export const main: () => void;
export const run_benchmark: (a: number, b: number) => number;
export const universe_cells: (a: number) => number;
export const universe_height: (a: number) => number;
export const universe_new: (a: number, b: number) => number;
export const universe_pixel_buffer_ptr: (a: number) => number;
export const universe_render: (a: number) => void;
export const universe_tick: (a: number) => void;
export const universe_width: (a: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
